apiVersion: v1
kind: Namespace
metadata:
  name: terraform-controller
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: executions.terraformcontroller.cattle.io
  namespace: terraform-controller
spec:
  group: terraformcontroller.cattle.io
  names:
    kind: Execution
    plural: executions
    singular: execution
  scope: Namespaced
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: modules.terraformcontroller.cattle.io
  namespace: terraform-controller
spec:
  group: terraformcontroller.cattle.io
  names:
    kind: Module
    plural: modules
    singular: module
  scope: Namespaced
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: states.terraformcontroller.cattle.io
  namespace: terraform-controller
spec:
  group: terraformcontroller.cattle.io
  names:
    kind: State
    plural: states
    singular: state
  scope: Namespaced
  version: v1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    apps.kubernetes.io/component: controller
    apps.kubernetes.io/name: terraform-controller
  name: terraform-controller
  namespace: terraform-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    apps.kubernetes.io/component: controller
    apps.kubernetes.io/name: terraform-controller
  name: terraform-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: terraform-controller
  namespace: terraform-controller
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    run: terraform-controller
  name: terraform-controller
  namespace: terraform-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      run: terraform-controller
  template:
    metadata:
      labels:
        run: terraform-controller
        version: v0.0.3
    spec:
      containers:
      - args:
        - --namespace
        - terraform-controller
        command:
        - terraform-controller
        image: rancher/terraform-controller:latest
        name: terraform-controller
      serviceAccountName: terraform-controller
