apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: modules.terraformcontroller.cattle.io
  namespace: terraform-controller
spec:
  group: terraformcontroller.cattle.io
  version: v1
  names:
    kind: Module
    plural: modules
    singular: module
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: states.terraformcontroller.cattle.io
  namespace: terraform-controller
spec:
  group: terraformcontroller.cattle.io
  version: v1
  names:
    kind: State
    plural: states
    singular: state
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: executions.terraformcontroller.cattle.io
  namespace: terraform-controller
spec:
  group: terraformcontroller.cattle.io
  version: v1
  names:
    kind: Execution
    plural: executions
    singular: execution
  scope: Namespaced
