apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    run: terraform-controller
  name: terraform-controller
  namespace: terraform-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      run: terraform-controller
  template:
    metadata:
      labels:
        run: terraform-controller
        version: v0.0.3
    spec:
      containers:
      - args:
        - --namespace
        - terraform-controller
        command:
        - terraform-controller
        image: rancher/terraform-controller:latest
        name: terraform-controller
      serviceAccountName: terraform-controller
